import AppKit
import Foundation

// MARK: - ClipboardClassifier
// Inspects an NSPasteboard and determines the best ClipboardType.
// Priority: image > richText > url > text > file > unknown.

enum ClipboardClassifier {

    static func classify(pasteboard: NSPasteboard) -> ClipboardType {
        let types = Set(pasteboard.types ?? [])

        // Image — TIFF, PNG
        if types.contains(.tiff) || types.contains(.png) {
            return .image
        }

        // Rich text — RTF
        if types.contains(.rtf) || types.contains(NSPasteboard.PasteboardType("public.rtf")) {
            return .richText
        }

        // URL — check string content
        if let string = pasteboard.string(forType: .string), isHTTPURL(string) {
            return .url
        }

        // Plain text
        if types.contains(.string) {
            return .text
        }

        // File URL
        if types.contains(.fileURL) {
            return .file
        }

        return .unknown
    }

    // MARK: - Privacy & Concealment Detection
    
    /// Detects if the pasteboard item is marked as confidential or transient by password managers
    /// (1Password, Apple Keychain, Bitwarden, KeePassXC, LastPass, etc.)
    static func isConcealed(pasteboard: NSPasteboard) -> Bool {
        guard let types = pasteboard.types else { return false }
        
        let concealedIdentifiers: Set<String> = [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.AutoGeneratedType",
            "org.nspasteboard.TransientType",
            "de.petermaurer.TransientPasteboardType",
            "com.agilebits.onepassword",
            "com.typeit4me.clipping",
            "Pasteboard generator type",
            "net.sourceforge.macpass"
        ]
        
        for type in types {
            if concealedIdentifiers.contains(type.rawValue) {
                return true
            }
        }
        return false
    }

    // MARK: - Helpers

    static func isHTTPURL(_ string: String) -> Bool {
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        guard let url = URL(string: trimmed) else { return false }
        return url.scheme == "http" || url.scheme == "https" || url.scheme == "ftp"
    }
}
